version: '3.9'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.httpchallenge=true'
      - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
      - '--certificatesresolvers.myresolver.acme.email=admin@habeshanets.com'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './letsencrypt:/letsencrypt'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - config.env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=Host(`habeshanets.com`)'
      - 'traefik.http.routers.backend.entrypoints=websecure'
      - 'traefik.http.routers.backend.tls.certresolver=myresolver'

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - config.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/ssl:/var/lib/postgresql/ssl:ro
    user: postgres
    command:
      - 'postgres'
      - '-c'
      - 'ssl=on'
      - '-c'
      - 'ssl_cert_file=/var/lib/postgresql/ssl/server.crt'
      - '-c'
      - 'ssl_key_file=/var/lib/postgresql/ssl/server.key'

volumes:
  postgres_data:
