version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: habeshanets-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - config.env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:16
    container_name: habesha-postgres
    restart: always
    env_file:
      - config.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init/init-db.sh:docker-enterypoint-initdb.d/init-db.sh

volumes:
  pgdata:
