services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - config.env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
      - pgcerts:/var/lib/postgresql/certs

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - config.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgcerts:/var/lib/postgresql/certs

volumes:
  pgdata:
  pgcerts:
